#pragma warning(push)
#pragma warning(disable : 4996)
#include "application.h"
#include "wxWidgets_includes.h"
#pragma warning(pop)

#pragma comment(lib, "Ws2_32.lib")
#ifdef  _DEBUG
#pragma comment(lib, "C:/Code/vcpkg/packages/wxwidgets_x64-windows-static/debug/lib/wxbase32ud.lib")
#pragma comment(lib, "C:/Code/vcpkg/packages/wxwidgets_x64-windows-static/debug/lib/wxbase32ud_net.lib")
#pragma comment(lib, "C:/Code/vcpkg/packages/wxwidgets_x64-windows-static/debug/lib/wxbase32ud_xml.lib")
#pragma comment(lib, "C:/Code/vcpkg/packages/wxwidgets_x64-windows-static/debug/lib/wxmsw32ud_adv.lib")
#pragma comment(lib, "C:/Code/vcpkg/packages/wxwidgets_x64-windows-static/debug/lib/wxmsw32ud_aui.lib")
#pragma comment(lib, "C:/Code/vcpkg/packages/wxwidgets_x64-windows-static/debug/lib/wxmsw32ud_core.lib")
#pragma comment(lib, "C:/Code/vcpkg/packages/wxwidgets_x64-windows-static/debug/lib/wxmsw32ud_gl.lib")
#pragma comment(lib, "C:/Code/vcpkg/packages/wxwidgets_x64-windows-static/debug/lib/wxmsw32ud_html.lib")
#pragma comment(lib, "C:/Code/vcpkg/packages/wxwidgets_x64-windows-static/debug/lib/wxmsw32ud_media.lib")
#pragma comment(lib, "C:/Code/vcpkg/packages/wxwidgets_x64-windows-static/debug/lib/wxmsw32ud_propgrid.lib")
#pragma comment(lib, "C:/Code/vcpkg/packages/wxwidgets_x64-windows-static/debug/lib/wxmsw32ud_qa.lib")
#pragma comment(lib, "C:/Code/vcpkg/packages/wxwidgets_x64-windows-static/debug/lib/wxmsw32ud_ribbon.lib")
#pragma comment(lib, "C:/Code/vcpkg/packages/wxwidgets_x64-windows-static/debug/lib/wxmsw32ud_richtext.lib")
#pragma comment(lib, "C:/Code/vcpkg/packages/wxwidgets_x64-windows-static/debug/lib/wxmsw32ud_stc.lib")
#pragma comment(lib, "C:/Code/vcpkg/packages/wxwidgets_x64-windows-static/debug/lib/wxmsw32ud_webview.lib")
#pragma comment(lib, "C:/Code/vcpkg/packages/wxwidgets_x64-windows-static/debug/lib/wxmsw32ud_xrc.lib")
#pragma comment(lib, "C:/Code/vcpkg/packages/wxwidgets_x64-windows-static/debug/lib/wxscintillad.lib")
#else
#pragma comment(lib, "C:/Code/vcpkg/packages/wxwidgets_x64-windows-static/lib/wxbase32u.lib")
#pragma comment(lib, "C:/Code/vcpkg/packages/wxwidgets_x64-windows-static/lib/wxbase32u_net.lib")
#pragma comment(lib, "C:/Code/vcpkg/packages/wxwidgets_x64-windows-static/lib/wxbase32u_xml.lib")
#pragma comment(lib, "C:/Code/vcpkg/packages/wxwidgets_x64-windows-static/lib/wxmsw32u_adv.lib")
#pragma comment(lib, "C:/Code/vcpkg/packages/wxwidgets_x64-windows-static/lib/wxmsw32u_aui.lib")
#pragma comment(lib, "C:/Code/vcpkg/packages/wxwidgets_x64-windows-static/lib/wxmsw32u_core.lib")
#pragma comment(lib, "C:/Code/vcpkg/packages/wxwidgets_x64-windows-static/lib/wxmsw32u_gl.lib")
#pragma comment(lib, "C:/Code/vcpkg/packages/wxwidgets_x64-windows-static/lib/wxmsw32u_html.lib")
#pragma comment(lib, "C:/Code/vcpkg/packages/wxwidgets_x64-windows-static/lib/wxmsw32u_media.lib")
#pragma comment(lib, "C:/Code/vcpkg/packages/wxwidgets_x64-windows-static/lib/wxmsw32u_propgrid.lib")
#pragma comment(lib, "C:/Code/vcpkg/packages/wxwidgets_x64-windows-static/lib/wxmsw32u_qa.lib")
#pragma comment(lib, "C:/Code/vcpkg/packages/wxwidgets_x64-windows-static/lib/wxmsw32u_ribbon.lib")
#pragma comment(lib, "C:/Code/vcpkg/packages/wxwidgets_x64-windows-static/lib/wxmsw32u_richtext.lib")
#pragma comment(lib, "C:/Code/vcpkg/packages/wxwidgets_x64-windows-static/lib/wxmsw32u_stc.lib")
#pragma comment(lib, "C:/Code/vcpkg/packages/wxwidgets_x64-windows-static/lib/wxmsw32u_webview.lib")
#pragma comment(lib, "C:/Code/vcpkg/packages/wxwidgets_x64-windows-static/lib/wxmsw32u_xrc.lib")
#pragma comment(lib, "C:/Code/vcpkg/packages/wxwidgets_x64-windows-static/lib/wxscintilla.lib")
#endif // ! _DEBUG
#pragma comment(lib, "C:/Code/vcpkg/packages/libpng_x64-windows-static/lib/libpng16.lib")
#pragma comment(lib, "C:/Code/vcpkg/packages/zlib_x64-windows-static/lib/zlib.lib")
#pragma comment(lib, "Rpcrt4.lib")
#pragma comment(lib, "Comctl32.lib")

wxIMPLEMENT_APP(chat_client_gui_cpp);